ToDoList/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('list/',include('list.urls'))
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register,name='register')
]

list/urls.py
from django.urls import path
from list import views


app_name = 'list'

urlpatterns = [
    path('create/',views.create_task_view,name='create'),
    path('delete/<id>',views.delete_task_view,name='delete')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.ImageField(blank=True)

    def __str__(self):
        return self.user.username
    

list/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=255)
    

    
    def __str__(self):
        return self.title
    

core/forms.py
from django import forms
from django.contrib.auth.models import User
from core.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(max_length=255,widget=forms.PasswordInput)
    
    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

core/views.py
from django.shortcuts import render

from core import forms
from list.models import Task

from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

def index(request):

    if request.user.is_authenticated:
        tasks = Task.objects.filter(user=request.user)
        current_user = request.user.username
        context = {"tasks":tasks,"user":current_user,"is_in":True}
        
        return render(request,'core/index.html',context)

    else:
        return HttpResponseRedirect(reverse('core:login'))
        


def login_view(request):

    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user is not None:
            if user.is_active:
                login(request,user)

            return HttpResponseRedirect(reverse('core:index'))


    return render(request,'core/login.html')


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:login'))


def register(request):
    user_form = forms.UserForm()
    user_profile_info_form = forms.UserProfileInfoForm()
    context = {
        "user_form":user_form,
        "user_profile_info_form":user_profile_info_form
        }


    if request.method == "POST":
        user_form = forms.UserForm(request.POST)
        user_profile_info_form = forms.UserProfileInfoForm(request.POST) 

        if user_form.is_valid() and user_profile_info_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_profile = user_profile_info_form.save(commit=False)
            user_profile.user = user

            if 'profile_pic' in request.FILES:
                user_profile.profile_pic = request.FILES['profile_pic']

            user_profile.save()

            return HttpResponseRedirect(reverse('core:login'))

    return render(request,'core/register.html',context)

list/views.py
from django.shortcuts import render
from list.models import Task

from django.urls import reverse
from django.http import HttpResponseRedirect

from core.models import UserProfileInfo
from django.contrib.auth.models import User
from list.models import Task
from django.contrib.auth.decorators import login_required


@login_required
def create_task_view(request):


    if request.method == "POST":

        title = request.POST.get('title')
        current_user = User.objects.get(id=request.user.id)
       
        task = Task(title=title,user=current_user)
        task.save()
        
        return HttpResponseRedirect(reverse('core:index'))

    
def delete_task_view(request,id):

    task = Task.objects.get(id=id)
    task.delete()
    
    return HttpResponseRedirect(reverse('core:index'))

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>ToDoList</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'core:index'%}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">


            {% if is_in %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:logout'%}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:register'%}">Register</a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:login'%}">Login</a>
            </li>

            {% endif %}

            </ul>
        </div>
        </nav>

      {% block body_block %}

      {% endblock body_block %}

</body>
</html>

templates/core/index.html
{% extends 'core/base.html' %}

{% block body_block %}

<div class="main-container">
        <div id="menu-container">
            <div class="menu header">
                <h3 style="margin-bottom:20px">To Do List</h3>
            </div>
            <div class="add-task-container">
    
                 <form action="{% url 'list:create'%}" method="POST">
                    {%csrf_token%}
                    <div class="form-group">
                        <input type="text" placeholder=" task" name='title'>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-info">
                    </div>
                   
                </form>
            </div>

        </div>
    
        <div id="task-container">
            <h3 style="text-align:center; margin-bottom: 20px;">{{user|capfirst}}'s Tasks</h3>
            {% if task == "" %}
            <p class="task"> No tasks assigned for {{user|capfirst}}</p>
            {% else %}
            {% for task in tasks %}
            <div class="inner-task-container">
                <a class="task" href="{% url 'list:delete' id=task.id%}">{{task.title}}</a>
            </div>
            
            {% endfor %}
            {% endif %}
        </div>
    </div>


</div>

{% endblock body_block %}

templates/core/login.html
{% extends 'core/base.html' %}

{% block body_block %}

<div class="login-form-container">
  <h3 style="color:#68829E;">Login</h3>
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" name="username" placeholder="Username">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" name="password" class="form-control" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock body_block %}

templates/core/register.html
{% extends 'core/base.html' %}

{% block body_block %}
<div class="register-form-container">
    <h3 style="color:#68829E;">Register</h3>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{user_form.username.label}}</p><p>{{user_form.username}}</p>
    <p>{{user_form.email.label}}</p> <p>{{user_form.email}}</p>
    <p></p>{{user_form.password.label}}</p><p>{{user_form.password}}</p>
    {{user_profile_info_form.as_p}}
    <input type="submit" class="btn btn-primary" value="Register" style="margin-top: 10px;">
    </form>
</div>
{% endblock body_block %}

templates/list/list.html
{% extends 'core/base.html' %}

{% block body_block %}
<h2>List Block</h2>
<div class="container">
    <form action="{% url 'list:create'%}" method="POST">
        {% csrf_token %}
        <label for="title">Title: </label>
        <input type="text" name="title" placeholder="task">
        <input type="submit" value="Create">
    </form>
    <hr>
    {% for task in tasks %}
    <p>{{task.title}}</p>
    
    {% endfor %}
</div>
{% endblock body_block %}